name: ecs-initial-image
on:
  push:
    branches:
      - 'main'
    paths: 
      - '.github/workflows/ecs-initial-image.yaml'
      - 'ecs-initial-image/**'
  pull_request:
    paths: 
      - '.github/workflows/ecs-initial-image.yaml'
      - 'ecs-initial-image/**'

env:
  DOCKER_BUILD_SUMMARY: false
  DOCKER_BUILD_RECORD_UPLOAD: false

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    defaults:
      run:
        working-directory: 'ecs-initial-image'
    steps:
      - uses: 'actions/checkout@v6'
      - uses: 'actions/setup-node@v6'
        with:
          node-version-file: 'ecs-initial-image/package.json'
      - run: npm ci
      - run: npm run ci
      - run: npm test

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    steps:
      - uses: 'actions/checkout@v6'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Log into registry ghcr.io
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/k-kojima-yumemi/ecs-initial-image:latest
          platforms: linux/amd64,linux/arm64
          context: 'ecs-initial-image'
          file: 'ecs-initial-image/Dockerfile'

  renovate-check:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions: {}
    needs:
      - test
      - build
    # See https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#needs-context for result values
    if: ${{ cancelled() || failure() }}
    steps:
      - run: 'false'
