name: postgres-health-check
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/postgres-health-check.yaml'
      - 'postgres-health-check/**'
  pull_request:
    paths:
      - '.github/workflows/postgres-health-check.yaml'
      - 'postgres-health-check/**'

env:
  DOCKER_BUILD_SUMMARY: false
  DOCKER_BUILD_RECORD_UPLOAD: false

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    defaults:
      run:
        working-directory: 'postgres-health-check/ts'
    steps:
      - uses: 'actions/checkout@v6'
      - run: docker compose up -d database
      - run: docker compose run --rm app npm ci
      - run: docker compose run --rm app npm run ci
      - run: docker compose run --rm app npm run build
      - name: Run test
        run: docker compose run --rm app npm test

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - test
    permissions:
      contents: read
      packages: write
    steps:
      - uses: 'actions/checkout@v6'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Log into registry ghcr.io
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/k-kojima-yumemi/postgres-health-check:latest
          platforms: linux/amd64,linux/arm64
          context: 'postgres-health-check/ts'
          file: 'postgres-health-check/ts/Dockerfile'

  renovate-check:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions: {}
    needs:
      - test
      - build
    if: ${{ cancelled() || failure() }}
    steps:
      - run: 'false'
